### ISSUE TITLE
[Feature Request] Being able to select the component instead of the default rootComponent

### ISSUE THREAD

**Issue by Shotman** [lukecyca/BoxMaker#1]
It would be nice ot be able to select which component to build the box in

**Comment by lukecyca** [comment]
Great idea!

Unfortunately I won't have time to implement this. If you want to give it a try, a PR would be more than welcome! I don't suspect it would be *that* difficult, but I don't know the F360 API very well, so the first step would to find another Python-based add-on that allows selecting a component, and review its code for the relevant bits.

**Comment by Shotman** [comment]
See PR #2
